import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/ui/ThemeProvider'
import ClientProviders from '@/components/ui/ClientProvider'
import FirebaseAuthProvider from '@/components/FirebaseAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'oh hello there bazinga',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClientProviders>

    <html lang="en">
      <body className={inter.className}>
        <FirebaseAuthProvider>

        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>

        <Header/>
        
        {children}
        </ThemeProvider>
          </FirebaseAuthProvider>
        </body>
    </html>
          </ClientProviders>
  )
}
